thisisparker/xword-dl

xword_dl.py
What started as a pretty targeted rewrite turned into something of a major refactor because as I was touching various parts of the script it made sense to make them all a little better. Notably, this PR should close:
- #10, which was the original point
- #8, which became kind of a freebie
- #13, which made it easier to fix the preceding two
Hopefully the classes are a little easier to follow now, too!
=> Refactor to consolidate some common Amuse reader functionality

README.md, xword_dl.py
More or less closes #22, although I may want to leave that around until I have `find_by_date` methods in these classes.
=> add basic support for downloading latest Vox and Daily Beast puzzles

README.md, xword_dl/downloader/globeandmaildownloader.py, xword_dl/xword_dl.py
This set of changes should support search-by-date, search-by-URL, and find-latest.
=> Add support for The Globe And Mail daily cryptic

xword_dl/downloader/amuselabsdownloader.py, xword_dl/downloader/basedownloader.py, xword_dl/downloader/globeandmaildownloader.py, xword_dl/downloader/guardiandownloader.py, xword_dl/downloader/newyorkerdownloader.py, xword_dl/downloader/newyorktimesdownloader.py, xword_dl/downloader/wsjdownloader.py, xword_dl/xword_dl.py
Still not quite ready to cut a release, but this improves (and consolidates) the NYT and NYT Variety code, addresses #74 by implementing #73, and tightens some logic around custom filenames, etc.
=> Merge in development branch

README.md, xword_dl/downloader/derstandarddownloader.py
Hi @thisisparker 
Following the workflow used in #76 I also created a downloader for the crosswords published by ['Der Standard'](https://www.derstandard.at/lifestyle/raetsel-sudoku/kreuzwortraetsel) a major news outlet from Austria.
Looking forward to your feedback.
Regards,
Petra
=> add downloader for Der Standard

xword_dl/downloader/amuselabsdownloader.py
there is almost certainly a way to do this that unifies the approaches and future-proofs against further changes so maybe we want to do that instead of merging this?
=> AmuseLabs fix

xword_dl/downloader/compilerdownloader.py
It works on the most recent Modern Crossword
=> Circles in compilerdownloader

README.md, xword_dl/downloader/crosswordclubdownloader.py
Hi @thisisparker,
As mentioned in #100 I also worked on a downloader for *Crossword Club*.
Looking forward to your feedback on this.
Regards,
Petra
=> add Crossword Club downloader

xword_dl/downloader/newyorkerdownloader.py
Fixes #109, but could use a little more testing.
=> Fix new yorker download with new selector

xword_dl/downloader/wsjdownloader.py
=> Check for non-puzzle wsj posts

.github/workflows/publish-release.yml
Updates #105 (and if successful, will fix it). I don't know of a way to test this without actually mucking around in the repo, so I will now proceed to muck around in the repo.
=> Attempt at github action

xword_dl/downloader/amuniversaldownloader.py
This switches the download source for USA Today from JSON (which has been a little flakily populated over the last month) to XML.
Fixes #122.
=> USAT: add alternate downloader

xword_dl/downloader/amuselabsdownloader.py
Slight change to key regex after Amuse updated some minification
=> amuselabs: tweak to key-finding regex

xword_dl/downloader/newyorkerdownloader.py
=> newyorkerdownloader: fix encoding error for theme titles

xword_dl/downloader/amuselabsdownloader.py
A lot of this downloader could use a refactor at this point, but I think this works and fixes #150.
=> amuselabs: fix for moved parameters

xword_dl/downloader/mckinseydownloader.py
=> mckinsey: fix typo affecting september puzzles

xword_dl/downloader/basedownloader.py
Small clean-up change, maybe updates #92
=> basedownloader: move filename option to settings object for both reading and writing

.github/workflows/status-check-outlets.yml
I think I'm going to have to test this pretty much live in the repo, so let's give it a shot
=> Commit testing action with partial list for checking

.github/workflows/status-check-outlets.yml, README.md, xword_dl/downloader/puzzlesocietydownloader.py
Alas! It's a great puzzle! But now behind a paywall and without an obvious way to provide credentials outside a browser context.
=> modern: remove puzzle for now, behind paywall

xword_dl/downloader/newyorkerdownloader.py
Use the embedded `application/ld+json` blob instead of parsing from the rendered components
=> tny: new logic to find latest puzzles

.github/workflows/status-check-outlets.yml, README.md, xword_dl/downloader/puzzmodownloader.py
Still slightly limited (no support for circled/shaded squares or rebuses) but appears to be working. I don't think there's a public Python parser for their data format (`.xd`) so this quick&dirty one will have to do :)
=> Add support for Puzzmo as an outlet

xword_dl/downloader/puzzmodownloader.py
The Puzzmo format spec allows for much more customization than .puz does, so as with other outlets I am converting any kind of markup to "circles".
=> puzzmo: add circle support

.github/workflows/status-check-outlets.yml, README.md, xword_dl/downloader/dailypopdownloader.py
This is cherry-picked from an old commit that I'd never gotten around to merging into `main`, but it's time.
=> dailypop: Add support for Daily Pop as an outlet

.github/workflows/publish-release.yml
Hit an error before, going to try updating to a newer version of the workflow and see if that fixes things!
=> update the publishing workflow in github actions

xword_dl/downloader/wapodownloader.py
=> wapo: fix downloader with new picker URL

xword_dl/downloader/derstandarddownloader.py
=> Der Standard: update CSS selector to fix latest download

xword_dl/downloader/puzzmodownloader.py
Plus a ruff formatting and some small typing fixes.
Fixes #243
=> Puzzmo Big: New date logic to accomodate switch from every-two-weeks to monthly

.github/workflows/status-check-outlets.yml, xword_dl/downloader/wapodownloader.py
New downloader to handle the new non-Amuse solver on the Sunday puzzle there.
Known limitations, for now:
- the "find latest" is kind of a cop-out and just pulls the most recent Sunday in Eastern time. Probably almost always right but I would prefer to find a way to actually get the latest
- currently no support at all for rebuses or circles or shade, as I don't yet know how the new format handles them
=> WaPo: new Washington Post downloader

xword_dl/downloader/amuniversaldownloader.py, xword_dl/downloader/amuselabsdownloader.py, xword_dl/downloader/basedownloader.py, xword_dl/downloader/compilerdownloader.py, xword_dl/downloader/crosswordclubdownloader.py, xword_dl/downloader/dailybeastdownloader.py, xword_dl/downloader/dailypopdownloader.py, xword_dl/downloader/globeandmaildownloader.py, xword_dl/downloader/guardiandownloader.py, xword_dl/downloader/latimesdownloader.py, xword_dl/downloader/mckinseydownloader.py, xword_dl/downloader/newsdaydownloader.py, xword_dl/downloader/newyorkerdownloader.py, xword_dl/downloader/newyorktimesdownloader.py, xword_dl/downloader/puzzlesocietydownloader.py, xword_dl/downloader/simplydailydownloader.py, xword_dl/downloader/voxdownloader.py, xword_dl/downloader/wsjdownloader.py, xword_dl/util/__init__.py, xword_dl/util/utils.py
A pass through the ruff formatter and linter. Many changed lines but they're mostly swapping in double-quotes and fixing indentation, which I think is good
=> ruff lint and formatting

xword_dl/xword_dl.py
=> Properly pass kwargs to the downloader for an embedded puzzle

xword_dl/downloader/derstandarddownloader.py
small rewrite matches for different CDN subdomains and different id formats
=> der standard: tweaks to regex

.github/workflows/status-check-outlets.yml, README.md, src/xword_dl/downloader/amuselabsdownloader.py, src/xword_dl/downloader/walrusdownloader.py
Adds support for TheWalrus.ca, a fine Canadian outlet with crosswords by fine Canadian constructors
=> add The Walrus downloader

.github/workflows/status-check-outlets.yml, README.md, src/xword_dl/downloader/amuselabsdownloader.py, src/xword_dl/downloader/billboarddownloader.py
=> Add AmuseLabs `idx` query support, and new outlet Billboard that uses it
