xword_dl.py

Prior to Python 3.6, `json.loads` did not automatically decode Unicode-encoded bytes-like objects. This adds an explicit UTF-8 decode after the base64 decode, so that it will work in earlier versions of Python.

Compatibility fix for Python 3.5 and earlier

---

xword_dl.py

These changes accomplish a few things:
* Make download() return a Puzzle.
* Remove dl.save_puz() and have a free function `save_puzzle(puzzle, filename)`.
Along the way we clean up the code path for picking a filename automatically if the user doesn't explicitly pass the `-o` argument.
A bad smell from the original code is that the downloader object is a big ball of mutable state with various concerns, which tries to share some code via inheritance.  However, in the inherited methods it is not always clear what part of the state should be already set or not.
May I suggest that you read the commits from oldest to newest; each individual commit tries to be a small refactoring operation that doesn't change the behavior of the code.
The changes are done with this mindset:
* Each downloader …

A little drive-by refactoring

---

README.md
xword_dl.py

- new `by_keyword` and `by_url` top level functions (in preparation for better embedding use)
- support for arbitrary URLs with embedded AmuseLabs solvers
- improved formatting and copy for help text
- replace explicit sys.exit() calls with errors for better error handling
- improved WSJ puzzle search
- print errors to `stderr` and output cleaner `stdout` if not in a tty

Bump for new release

---

xword_dl.py

This will let you save into other directories (eg. 'xword-dl -o /tmp/temp.puz') as well as let you output the .puz file directly to stdout.

Add some flexibility to how xword-dl saves files

---

xword_dl/xword_dl.py

Hi @thisisparker 👋🏼 
While trying to download crosswords[^1] from McKinsey's [*The McKinsey Crossword*](https://www.mckinsey.com/featured-insights/the-mckinsey-crossword) I noticed a possible **bug** in line [78](https://github.com/thisisparker/xword-dl/blob/89bfffea9933958f8e38134753b7479cd9263ec1/xword_dl/xword_dl.py#L78) of [`xword_dl.py`](https://github.com/thisisparker/xword-dl/blob/89bfffea9933958f8e38134753b7479cd9263ec1/xword_dl/xword_dl.py#L78).
```python
dl = AmuseLabsDownloader(netloc=netloc)
```
Afterwards I managed to successfully **download** crosswords with:
```bash
xword-dl https://www.mckinsey.com/featured-insights/the-mckinsey-crossword/november-8-2022
```
I also tried to write a **downloader** class for *The McKinsey Crossword* however I **failed** to find the *date …

fix import of AmuseLabsDownloader

---

requirements.txt
xword_dl/downloader/compilerdownloader.py
xword_dl/xword_dl.py

This improves the existing `by_url` search a bit and also adds a check for Crossword Compiler widgets in script tags and any iframe script tags. (To support that, this also adds a `CrosswordCompilerDownloader` to the downloader sub-package, which hopefully will be reusable later.)
Support is currently partial as it works in some places:
```xword-dl "https://www.brendanemmettquigley.com/2022/11/crossword-1522-themeless-monday.html"```
but not others:
```xword-dl "https://www.theglobeandmail.com/puzzles-and-crosswords/cryptic-crossword/?date=121122&T=0"```

add partial support for crossword compiler widgets embedded in pages for by_url search

---

requirements.txt

bs4 is a [dummy module](https://pypi.org/project/bs4/), and we already include the real one here ([beautifulsoup4](https://pypi.org/project/beautifulsoup4/)), so drop it.

drop bs4 from requirements

---

xword_dl/downloader/mckinseydownloader.py

Hi @thisisparker 
I just noticed that McKinsey has slightly adapted the frontend of *The McKinsey Crossword*.
This caused the download to fail. I slightly adapted the css selector required to identify the amuselabs iframe node.
Regards,
Petra

fix selection of amuselabs iframe of The McKinsey Crossword

---

xword_dl/downloader/atlanticdownloader.py

Regular Atlantic puzzles have a predictable ID from which we can deduce the puzzle date, but the new [Caleb's Inferno](https://www.theatlantic.com/calebs-inferno-crossword-puzzle/) puzzle does not. This fixes a crash when encountering one of those puzzles.

Fix date guesser for atlantic puzzles

---

setup.py

Working toward solving #115 
On Windows 11, using Powershell, VS Code, and Python 3.11.5. Ran into exceptions into setup.py while playing around. On windows, open() defaults to cp1252 instead of utf-8. :-( Just starting with the project and this was the first thing I encountered. I suspect @thisisparker uses Mac or Linux.

Explicitly define encoding as utf-8

---

xword_dl/downloader/newyorktimesdownloader.py

I've deliberately been pretty liberal with what gets the "circled" markup on NYT puzzles, because they have more `type`s than the .puz spec and it seems worse to silently drop highlighted squares. But that has inadvertently resulted in the circled markup getting applied to black squares, which could create some subtle bugs in solving clients.

NYT: Return plain markup type for black squares

---

xword_dl/downloader/newyorkerdownloader.py

Fixes #111.
@edsantiago, would love if you could take a look at this and make sure it meets your needs! Two sort of compromise-y elements is that it uses the `description` field (which seems stable and a little easier to target than the subhed) and it loads a little more logic into the `pick_filename` function, but that seemed to be the best way to preserve existing behavior where desired and push out past it for this feature.

New Yorker: Add theme title to Friday puzzles

---

README.md
xword_dl/downloader/newyorktimesdownloader.py

Technically you can still download by date, if you know the date to pick!

NYTV: remove Variety download-by-latest and download-by-url options

---

xword_dl/downloader/wsjdownloader.py

Recent Friday contest puzzles have been posted without a solution; this PR allows `xword-dl` to correctly create solutionless puz files from that data, and also updates the source of Note information to match where WSJ is putting it.

WSJ: Better handle Friday contest puzzles

---

xword_dl/downloader/wsjdownloader.py

Some metadata fields were not being processed into `latin-1`, breaking puz support.

WSJ: run fetched text fields through unidecode for inclusion in puz

---

xword_dl/downloader/amuniversaldownloader.py

On at least one recent day, the online puzzle data was malformed XML. This PR adds a check to fail more gracefully in that situation.

USAT: add check for malformed xml data

---

xword_dl/downloader/puzzlesocietydownloader.py

Debugging this one went quickly from "why doesn't this work?" to "why did this ever work?" but all good now

the modern: fix typo in initialize function

---

requirements.txt
xword_dl/downloader/amuniversaldownloader.py
xword_dl/downloader/amuselabsdownloader.py
xword_dl/downloader/basedownloader.py
xword_dl/downloader/compilerdownloader.py
xword_dl/downloader/guardiandownloader.py
xword_dl/downloader/newyorkerdownloader.py
xword_dl/downloader/newyorktimesdownloader.py
xword_dl/downloader/wsjdownloader.py
xword_dl/util/utils.py

A little refactor that touches a handful of downloaders, this change moves the "cleanup" step required for various text fields to fit into the constraints of .puz into one central location. That simplifies each downloader a bit and should help avoid bugs where new fields aren't sanitized correctly.
Along the way, we pick up a new dependency, alas. This new emoji library converts :fire: to `:fire:`. That is better for readability than just dropping the emoji, and also should be losslessly reversible client-side if desired.
Fixes #148 
Fixes #155

centralize encoding cleanup and add emoji processing step

---

xword_dl/downloader/dailybeastdownloader.py

Remove the periods from the title before parsing for a date. `dateparser`'s search splits on periods, which seems like a thing they should fix, but this workaround works.

dailybeast: improve date parsing from title

---

xword_dl/downloader/mckinseydownloader.py

McKinsey's class names have not been totally stable, but the link order seems to be. I think it's enough to grab the first one that matches this path start

mckinsey: less selector specificity but probably still enough

---

xword_dl/downloader/amuselabsdownloader.py
xword_dl/downloader/newyorktimesdownloader.py
xword_dl/util/utils.py

The specter of `unidecode` still haunts downloaders, as it turns out we may need to sanitize the contents of rebus squares in some cases (and at least for now, those are encoded in the individual downloader so we can't save it for later like we can the other fields.
Fixes #171

{amuse,nyt}: sanitize rebus inputs

---

.github/workflows/status-check-outlets.yml
xword_dl/downloader/newyorktimesdownloader.py
xword_dl/downloader/puzzlesocietydownloader.py

In some cases, NYT puzzle data encodes squares that are canonically blank. The .puz format doesn't support blank solution answers, but fortunately in every example I've seen so far, there is a `moreAnswers` field to allow rebus entry. This is sort of kludge-y because it collapses the possible rebus answers down to the first one provided, but it is a valid file and a decent approximation.
Fixes #170
Fixes #154

nytimes: accommodate moreAnswers field for otherwise blank squares

---

.github/workflows/status-check-outlets.yml
xword_dl/downloader/newyorktimesdownloader.py

If no text is provided for a clue, then put no text in! Fair enough.
Updates #175

nytimes: accomodate blank clues

---

.github/workflows/status-check-outlets.yml
xword_dl/downloader/newyorkerdownloader.py

Previously we'd handled the "theme title" at the filename selection phase, but that would allow edits to the puz file data after it had been sanitized. This fixes that issue and adds a CI test to catch future regressions.

newyorker: move theme title handling and test

---

.github/workflows/status-check-outlets.yml
xword_dl/downloader/basedownloader.py
xword_dl/downloader/wsjdownloader.py

This change creates a requests Session object at the BaseDownloader level and loads it with the `headers` and `cookies` that are specified in a config file, as keyword arguments, or command line arguments. In part this keeps us from having to repeat ourselves in instances where we have multiple requests that require the same arguments, and it should slightly simplify the story for new downloaders.
All the old-style downloaders will continue to work, but should eventually be updated to use the Session established by the BaseDownloader. For this PR, I've updated the WSJ downloader to the new syntax in order to put together a fix for #178. I've also attempted to update the tests that it uses... we'll see!

wsj, base: Move requests to a session object that can accept settings

---

xword_dl/downloader/guardiandownloader.py

The attribute previously used to find puzzle links changed. Rather than update it to a new one, take the first link in the page matching the puzzle URL format, as this should be more reliable.
Fixes #190.

Fix Guardian puzzle downloader

---

xword_dl/downloader/crosswordclubdownloader.py

It looks like Crossword Club is running on its own path at Amuse. This minimal change appears to work!

club: change iframe selector to match new site

---

.github/workflows/status-check-outlets.yml
README.md
xword_dl/downloader/wsjdownloader.py

Until #178 is resolved, WSJ should not be listed as a supported platform.

wsj: remove WSJ from supported platforms

---

requirements.txt

`lxml` 4.9.2, the version currently required by `xword-dl`, does not have precompiled wheels available for Python 3.12 (see https://pypi.org/project/lxml/4.9.2/#files), whereas `lxml` 4.9.3 and newer do. This commit updates the requirement for `lxml` to 5.1.0 (the latest available version) to allow for installing `xword-dl` locally under Python 3.12 without having to locally build a wheel for `lxml`.
(Thank you for your work on `xword-dl`, I use it often. 🙂)

update lxml requirement from 4.9.2 to 5.1.0

---

xword_dl/xword_dl.py

This prevents an issue where the `src` has been provided as `about:blank` and the useful data in `data-src` or a crossword specific tag is ignored (as observed with TNY Mini puzzle pages).

xword_dl: reorder iframe source check from most to least specific

---

xword_dl/downloader/amuselabsdownloader.py

This reflects a change that appears to have happened on AmuseLab's end. Should fix LAT, Vox, Newsday, and Daily Beast downloaders.
Fixes #218

amuselabs: rename pickerToken to loadToken

---

xword_dl/downloader/guardiandownloader.py

This updates the target for scraping on Guardian pages to reflect a change they made on their end.
Fixes #216

guardian: update location of data on page

---

.github/workflows/status-check-outlets.yml
README.md
xword_dl/downloader/globeandmaildownloader.py

This PR removes The Globe and Mail's cryptic, which was discontinued earlier this year in favor of syndicating one by The Times, and updates the Github Actions workflow and README to reflect that change.
Fixes #212

Remove Globe and Mail from supported downloaders

---

.github/workflows/status-check-outlets.yml
README.md
setup.py
xword_dl/downloader/puzzmodownloader.py

This refactors the graphql query from the existing Puzzmo downloader and adds support for Puzzmo Big. Both channels only have "latest" support, and archives would require some auth. It's possible that this will be short-lived as the Big Crossword is supposed to be going behind the paywall soon anyway!
Fixes #211.
Fixes #213.

puzzmo: add puzzmo big, and by-date and by-URL search for both

---

xword_dl/xword_dl.py

The `url` value is used in the BaseDownloader constructor to set its `netloc` and to inherit settings from that value and from the `url` parent, so we should be passing it!

fixup: pass url as a kwarg to downloader from embedded solver

---

.github/workflows/publish-release.yml

I believe this is necessary for the publish action to create a draft release

publish workflow: add contents write permission

---

src/xword_dl/downloader/compilerdownloader.py
src/xword_dl/downloader/dailypopdownloader.py
src/xword_dl/downloader/globeandmaildownloader.py
src/xword_dl/downloader/simplydailydownloader.py

This simplifies the fetch functions and fixes embeds, which only worked for the JS-encoded version anyway.

compiler: break js-encoded compiler downloader into subclass

---

src/xword_dl/downloader/derstandarddownloader.py

This fixes failing Der Standard downloads over the last few days but I can't help but feel like the better solution is to move this logic up a level, as discussed in #270 and others

der standard: allow dashes in amuselabs ids

---

.github/workflows/status-check-outlets.yml
README.md
src/xword_dl/downloader/mckinseydownloader.py

Alas, another one bites the dust. McKinsey is doing some browser fingerprinting that I can't figure out how to get around, so I've had to turn this one off.
Closes #274

Remove McKinsey downloader, as it has stopped working due to anti-scraping techniques

---

src/xword_dl/downloader/amuselabsdownloader.py
src/xword_dl/downloader/basedownloader.py
src/xword_dl/downloader/compilerdownloader.py
src/xword_dl/xword_dl.py

Previously, when `xword-dl` was invoked by URL, the `parse_for_embedded_puzzle` function would extract a bunch of candidate URLs that might be suitable puzzle URLs, and then those would be evaluated one-by-one by appropriate downloader classes.
In this new approach, `parse_for_embedded_puzzle` grabs the page source and passes _that_ to a matching function in the relevant downloaders. I think this is cleaner, and it also allows the analysis in each downloader to be a little more specific. That in turn should open the door to embeds that use some technique other than an iframe source: I'm thinking in particular about the AmuseLabs JS embeds (as with the DerStandardDownloader, currently) but it may also apply to upcoming Crosshare puzzles.
One gotcha while implementing this is that only …

refactor page parsing approach, moving more logic to plugins

---

src/xword_dl/downloader/observerdownloader.py

Silly copy and paste error, wasn't stopping downloads but was complicating metadata.

observer: fix typo in speedy url matching

---

src/xword_dl/downloader/amuselabsdownloader.py

The date-picker page for Amuse outlets had been created server-side, so we previously parsed its HTML to pick the latest puzzle. Now they appear to be including a JSON array of puzzles and populating the page from it, so now we look at that JSON source too.

amuse: switch to using `params` to find latest from date-picker

---

src/xword_dl/downloader/basedownloader.py
src/xword_dl/downloader/newyorkerdownloader.py

Some outlets screen for the `requests` UA string and we'd been manually setting a User-Agent in those cases, but it should be something configurable at the settings level, and it's good hygiene to be sending a meaningful UA string wherever we can.

BaseDownloader: Set default User-Agent string for downloaders if unset in settings
